apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backend","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"backend"}},"template":{"metadata":{"labels":{"app":"backend"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","value":"db-service"},{"name":"DB_USER","value":"dbadmin"},{"name":"DB_PASSWORD","value":"P@ssw00rd"}],"image":"us-east1-docker.pkg.dev/p-9016-group-18/nginx-app/backend:v1","name":"backend","ports":[{"containerPort":3000}]}]}}}}
    creationTimestamp: "2025-03-24T17:30:34Z"
    generation: 1
    name: backend
    namespace: default
    resourceVersion: "151932"
    uid: 3020c719-d577-48ff-938e-04d317199d5b
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: backend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: backend
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: db-service
          - name: DB_USER
            value: dbadmin
          - name: DB_PASSWORD
            value: P@ssw00rd
          image: us-east1-docker.pkg.dev/p-9016-group-18/nginx-app/backend:v1
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2025-03-24T17:30:36Z"
      lastUpdateTime: "2025-03-24T17:30:36Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-03-24T17:30:34Z"
      lastUpdateTime: "2025-03-24T17:30:36Z"
      message: ReplicaSet "backend-5cd6d99b66" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"db-server","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"db"}},"template":{"metadata":{"labels":{"app":"db"}},"spec":{"containers":[{"command":["/cloud_sql_proxy","-instances=p-9016-group-18:us-east1:social-db=tcp:5432","-credential_file=/secrets/cloudsql/credentials.json"],"image":"gcr.io/cloudsql-docker/gce-proxy:latest","name":"cloudsql-proxy","ports":[{"containerPort":5432}],"volumeMounts":[{"mountPath":"/secrets/cloudsql","name":"cloudsql-instance-credentials","readOnly":true}]},{"env":[{"name":"POSTGRES_USER","value":"dbadmin"},{"name":"POSTGRES_PASSWORD","value":"P@ssw00rd"},{"name":"POSTGRES_DB","value":"social_media"},{"name":"DB_HOST","value":"127.0.0.1"}],"image":"postgres:14","name":"postgres-container","ports":[{"containerPort":5432}]}],"volumes":[{"name":"cloudsql-instance-credentials","secret":{"secretName":"cloudsql-instance-credentials"}}]}}}}
    creationTimestamp: "2025-03-24T16:24:51Z"
    generation: 2
    name: db-server
    namespace: default
    resourceVersion: "111374"
    uid: b3f3804b-9a97-43a8-abda-36913ae366f1
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: db
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2025-03-24T16:30:07Z"
        creationTimestamp: null
        labels:
          app: db
      spec:
        containers:
        - command:
          - /cloud_sql_proxy
          - -instances=p-9016-group-18:us-east1:social-db=tcp:5432
          - -credential_file=/secrets/cloudsql/credentials.json
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          imagePullPolicy: Always
          name: cloudsql-proxy
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /secrets/cloudsql
            name: cloudsql-instance-credentials
            readOnly: true
        - env:
          - name: POSTGRES_USER
            value: dbadmin
          - name: POSTGRES_PASSWORD
            value: P@ssw00rd
          - name: POSTGRES_DB
            value: social_media
          - name: DB_HOST
            value: 127.0.0.1
          image: postgres:14
          imagePullPolicy: IfNotPresent
          name: postgres-container
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: cloudsql-instance-credentials
          secret:
            defaultMode: 420
            secretName: cloudsql-instance-credentials
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-03-24T16:25:05Z"
      lastUpdateTime: "2025-03-24T16:25:05Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-03-24T16:24:52Z"
      lastUpdateTime: "2025-03-24T16:30:10Z"
      message: ReplicaSet "db-server-78794c46c6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "8"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"web-app","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"env":[{"name":"TZ","value":"America/New_York"}],"image":"us-east1-docker.pkg.dev/p-9016-group-18/nginx-app/webapp:v1","name":"nginx-container","ports":[{"containerPort":80}]}]}}}}
    creationTimestamp: "2025-03-24T16:01:09Z"
    generation: 9
    name: web-app
    namespace: default
    resourceVersion: "152674"
    uid: 4ffdf45e-ef13-4db0-8060-7264b0f65d75
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nginx
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2025-03-24T16:57:04Z"
        creationTimestamp: null
        labels:
          app: nginx
      spec:
        containers:
        - env:
          - name: TZ
            value: America/New_York
          image: us-east1-docker.pkg.dev/p-9016-group-18/nginx-app/webapp:v4
          imagePullPolicy: Always
          name: nginx-container
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2025-03-24T16:45:03Z"
      lastUpdateTime: "2025-03-24T16:45:03Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-03-24T16:01:09Z"
      lastUpdateTime: "2025-03-24T17:31:37Z"
      message: ReplicaSet "web-app-576fcc9b69" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 9
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
