apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx  # Must match your web-app deployment labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
